name: submission
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  image_picker:
  image_cropper:
  camera: ^0.10.4+1

  tflite_flutter: ^0.11.0
  image:
  path_provider:

  firebase_core: ^4.1.1
  firebase_ml_model_downloader: ^0.4.0+2
  http: ^1.5.0
  google_generative_ai:
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
